### ISSUE TITLE
PageSigner error in Chrome.

### ISSUE THREAD

**Issue by MuhammedZakir** [tlsnotary/pagesigner#12]
Hello! I added PageSigner to Chrome today but I can not sign any of the webpages. It gives me below error:

> PageSigner error
> This website cannot be audited by PageSigner because it presented an untrusted certificate

I am using Chrome Canary in Windows. Any fix for this? Thank you!

**Comment by AdamISZ** [comment]
Hi; there's several possible ways this could happen. Make sure you're opening pages after you installed PageSigner. Make sure that the certificate is trusted (check the padlock on the browser). It might also be connected with Chrome Canary. If it's something else we'll need to do more debugging.

You can reach us at: #tlsnotary-chat (on Freenode IRC).

Also on reddit if you like: reddit.com/r/tlsnotary (my username is waxwing)

**Comment by MuhammedZakir** [comment]
@AdamISZ I also tried using Chrome. It is still showing that error. I first tried to install PageSigner in Mozilla but the latest version is incompatible. I am getting this error especially in Bitcointalk.org. I was able notarize Github page. When I tried to notarize I2P webpage, I got

> PageSigner error
> connect: socket timed out

Hope you can fix it!

**Comment by AdamISZ** [comment]
@MuhammedZakir glad to hear you were able to get a notarization :)

About the bitcointalk.org failure:
@themighty1 recently noticed a problem specifically with bitcointalk.org, to do with certificates being provided in the incorrect order. See https://bugzilla.mozilla.org/show_bug.cgi?id=1160936

We should probably edit the code to allow this (bitcointalk.org always worked fine until very recently), since TLS clients are apparently accepting this, in contradiction to the RFCs.

As for I2P, there has been no attempt to support that. We'd have to look into it I guess.

Do you have other https sites on Chrome or Firefox that don't work (i.e. fail with 'untrusted certificate'?).

**Comment by AdamISZ** [comment]
> I first tried to install PageSigner in Mozilla but the latest version is incompatible.

Do you mean Firefox 39.0?
There definitely should be no problem with FF 38, but I haven't tried 39 yet.

**Comment by AdamISZ** [comment]
@MuhammedZakir I've just pushed a commit which fixes the error in Chrome. ea32e875015bcd0d4444f3bb574ecef5d67d3787

If you download from https://tlsnotary.org/pagesigner.html, you'll get the latest version. This patch fixes the bitcointalk.org issue you mentioned (as I said above, it was due to certificates being delivered in the wrong order by the server).

Let me know if any issues persist.

**Comment by MuhammedZakir** [comment]
@AdamISZ Thank you! I have installed new version on Chrome. ATM PageSigner is showing

> PageSigner error
> Cannot notarize because something is wrong with PageSigner server. Please try again later

So, will try notarizing later and will report here. Hope it works!

**Comment by AdamISZ** [comment]
@MuhammedZakir  OK. That's very strange; the server is definitely operating fine right now, I just tested it (in fact it hasn't gone down since it started about 3 months ago, and it isn't likely to). There may be some internet connectivity problem. Alternatively, if you reset the default notary server IP, but that seems unlikely.

If it persists, let us know.

**Comment by MuhammedZakir** [comment]
@AdamISZ It is working now! Thank you for your fast response. Btw, did you leave Bitcointalk.org?

**Comment by AdamISZ** [comment]
@MuhammedZakir no, just, there was no point responding to you there, since I already responded here :)

Glad it's working finally!

**Comment by MuhammedZakir** [comment]
@AdamISZ Okay, got it! I understand. Thank you for your works! Keep it up!

 I am still unable to notarize I2P webpage(https://geti2p.net). Getting

> PageSigner error
> connect: socket timed out

I will keep this open until this is resolved.

**Comment by AdamISZ** [comment]
Hi.

Just tried that page on Firefox and Chrome, both worked. I will ask others to try.

**Comment by AdamISZ** [comment]
@MuhammedZakir Well, I don't have more evidence unfortunately, but my working hypothesis is that it may well be your internet connection. I'm going to close this issue; it would be better to have specific issues for specific problems (or just debug on IRC or other places). If you find this problem is repeatable, and specific to that site, please open another issue.

**Comment by traconis** [comment]
Every time I trying to sign a page I getting the same error (Firefox and Chrome)
"You are signing pages to fast. Please retry in 60 sec".
This is the first time I trying to use that extensions - haven't notarize any pages before and waiting one hour doesnt help :(

**Comment by pavoltravnik** [comment]
Server is probably not running. I got an error
"Cannot notarize because something is wrong with PageSigner server. Please try again later."

**Comment by themighty1** [comment]
Thanks for the heads up. PageSigner on Chrome is working on my end. The oracle server is running as usual.

**Comment by pavoltravnik** [comment]
> Thanks for the heads up. PageSigner on Chrome is working on my end. The oracle server is running as usual.

Is there any different approach how to install the app? I am really stuck in this point and have any leads how to move forward.
![screen shot 2018-10-22 at 12 43 18](https://user-images.githubusercontent.com/21983609/47289558-a06ff700-d5fb-11e8-9cfb-a6cbf1ed13fa.png)

**Comment by pavoltravnik** [comment]
I got a lead "As of this writing, TLSnotary is only compatible with TLS 1.0 and 1.1, not TLS
1.2" but my PC uses 1.2 by default.

**Comment by themighty1** [comment]
@pavoltravnik There was a bug which was fixed in PageSigner v 1.1.2.2.  You may want to try this latest version and see if it works for you.

**Comment by pavoltravnik** [comment]
Well thank you! It works now.
