### ISSUE TITLE
PageSigner.js library

### ISSUE THREAD

**Issue by lukehedger** [tlsnotary/pagesigner#28]
Is there a plan to build a PageSigner JavaScript library that could be consumed in a browser or Node.js?

One potential use case would be an application or program that allows users to specify the URL of a page they wish to notarize, performs the necessary verification and returns a signature.

Another would be an application or program that allows users to upload `.pgsg` files for validation.

Interested in whether this has been considered at all and to understand what would be involved in such a project.

**Comment by themighty1** [comment]
We haven't had such plans simple because there was no demand for it. However we already have https://github.com/tlsnotary/pagesigner-browserless which allows to notarize from a command line (note: it hasnt been updated yet to run with the latest PageSigner).

I dont see any impediment in building such JS lib except for a few things: PageSigner must have access to raw sockets in order to send its custom TLS packets.

**Comment by goga-m** [comment]
Hey @lukehedger @themighty1 

I ported the Pagesigner chrome extension to NodeJS. 
The core functionality and code is the same. Just removed the client-side related code and refactored some pieces and modularized it.

It may need some changes for but the basic functionality for notarizing and verifying is there.
https://github.com/goga-m/pagesigner.js

I hope it helps.
 
Thanks for the great service.

**Comment by themighty1** [comment]
@goga-m , we appreciate your efforts!
